Repository Deepractice/PromptX, pull requests merged in 2025-08, with the labels that each got.

#221 fix: 验证自动标签和发布控制 #219
  test-fix-219.md
Labels: type: fix, changeset/patch, publish/dev, merge/squash

#222 feat: 测试自动版本管理系统
  test-auto-version.md
Labels: changeset/minor, publish/dev, merge/squash

#223 fix: 修复工作流权限和发布流程
  test-workflow-v2.md
Labels: changeset/patch, merge/squash

#226 fix: 修复系统角色无法激活的问题 (#225)
  src/lib/core/resource/discovery/PackageDiscovery.js
Labels: changeset/patch, merge/squash

#235 fix: 提升ToolSandbox工作目录到~/.promptx层级 (#232)
  src/lib/tool/SandboxIsolationManager.js
  src/lib/tool/ToolDirectoryManager.js
  src/lib/tool/ToolSandbox.js
Labels: changeset/patch, merge/squash

#237 fix: 修复 ToolSandbox 对 scoped npm 包的解析问题 (#236)
  .promptx/resource/tool/tool-tester/tool-tester.manual.md
  .promptx/resource/tool/tool-tester/tool-tester.tool.js
  resource/role/luban/execution/tool-development-workflow.execution.md
  resource/role/luban/execution/toolsandbox-mastery.execution.md
  src/lib/tool/SandboxErrorManager.js
  src/lib/tool/ToolInterface.js
  src/lib/tool/ToolSandbox.js
Labels: type: fix, changeset/patch, changeset/major, merge/squash

#240 feat: 实现filesystem工具解决HTTP服务模式文件访问 (#230)
  .gitignore
  .promptx/resource/role/cognition/cognition.role.md
  .promptx/resource/role/cognition/execution/memory-system.execution.md
  .promptx/resource/role/cognition/thought/cognitive-memory.thought.md
  .promptx/resource/role/darp/darp.role.md
  .promptx/resource/role/darp/execution/darp-workflow.execution.md
  .promptx/resource/role/darp/thought/protocol-thinking.thought.md
  .promptx/resource/role/dpml/dpml.role.md
  .promptx/resource/role/dpml/execution/dpml-philosophy.execution.md
  .promptx/resource/role/dpml/thought/consensus-thinking.thought.md
  .promptx/resource/role/mcp-architect/execution/mcp-development-workflow.execution.md
  .promptx/resource/role/mcp-architect/mcp-architect.role.md
  .promptx/resource/role/mcp-architect/thought/mcp-design-thinking.thought.md
  .promptx/resource/role/pateoas/execution/pateoas-workflow.execution.md
  .promptx/resource/role/pateoas/pateoas.role.md
  .promptx/resource/role/pateoas/thought/state-navigation.thought.md
  .promptx/resource/role/promptx-architect/execution/architecture-workflow.execution.md
  .promptx/resource/role/promptx-architect/execution/technical-debate.execution.md
  .promptx/resource/role/promptx-architect/promptx-architect.role.md
  .promptx/resource/role/promptx-architect/thought/architectural-thinking.thought.md
  .promptx/resource/role/promptx-architect/thought/critical-analysis.thought.md
  .promptx/resource/role/toolsandbox-architect/execution/toolsandbox-workflow.execution.md
  .promptx/resource/role/toolsandbox-architect/thought/toolsandbox-thinking.thought.md
  .promptx/resource/role/toolsandbox-architect/toolsandbox-architect.role.md
  .promptx/resource/tool/filesystem/filesystem.manual.md
  .promptx/resource/tool/filesystem/filesystem.tool.js
  .serena/cache/typescript/document_symbols_cache_v23-06-25.pkl
  .serena/memories/project-architecture-analysis.md
  resource/package.registry.json
  resource/tool/filesystem/filesystem.manual.md
  resource/tool/filesystem/filesystem.tool.js
Labels: changeset/minor, merge/squash

#247 feat: 适配女娲和鲁班角色到新架构 (#245)
  .promptx/resource/tool/filesystem/filesystem.manual.md
  .promptx/resource/tool/filesystem/filesystem.tool.js
  CLAUDE.md
  resource/package.registry.json
  resource/role/luban/execution/tool-creation-filesystem.execution.md
  resource/role/luban/execution/tool-development-workflow.execution.md
  resource/role/luban/luban.role.md
  resource/role/nuwa/execution/role-creation-filesystem.execution.md
  resource/role/nuwa/execution/role-generation.execution.md
  resource/role/nuwa/nuwa.role.md
  src/lib/core/dpml/SemanticRenderer.js
  src/lib/core/pouch/commands/ActionCommand.js
  src/lib/core/pouch/commands/InitCommand.js
  src/lib/core/pouch/commands/WelcomeCommand.js
  src/lib/core/resource/discovery/FilePatternDiscovery.js
  src/lib/core/resource/protocols/ResourceProtocol.js
  src/lib/core/resource/protocols/UserProtocol.js
  src/lib/core/resource/resourceManager.js
Labels: type: feature, changeset/minor, merge/squash

#252 fix: 统一 MCP 传输层实现，使用 FastMCP 框架 (#248)
  CLAUDE.md
  package.json
  pnpm-lock.yaml
  src/bin/promptx.js
  src/lib/core/pouch/commands/ToolCommand.js
  src/lib/mcp/MCPServerHttpCommand.js
  src/lib/mcp/MCPServerStdioCommand.js
  src/lib/mcp/definitions/promptx_init.js
  src/lib/mcp/definitions/promptx_recall.js.backup
  src/lib/mcp/definitions/promptx_remember.js.backup
  src/lib/mcp/definitions/promptx_welcome.js
  src/lib/mcp/server/FastMCPHttpServer.js
  src/lib/mcp/server/FastMCPStdioServer.js
  src/lib/mcp/server/MCPHttpServerInterface.js
  src/lib/mcp/server/MCPStdioServerInterface.js
  src/lib/mcp/toolDefinitions.js
Labels: changeset/patch, merge/squash

#254 test: 验证基于 PR 标签的发布流程
  .changeset/test-publish-workflow.md
Labels: changeset/patch, publish/dev, merge/squash

#256 feat: 完整测试基于 PR 标签的发布工作流
  .changeset/complete-workflow-test.md
Labels: changeset/minor, publish/dev, merge/squash

#287 feat: [Discussion] 认知循环过程完整分析与优化讨论
  .changeset/1756012460-pr-287-minor.md
  src/bin/promptx.js
  src/lib/core/cognition/Anchor.js
  src/lib/core/cognition/CognitionManager.js
  src/lib/core/cognition/CognitionSystem.js
  src/lib/core/cognition/Consciousness.js
  src/lib/core/cognition/Engram.js
  src/lib/core/cognition/Remember.js
  src/lib/core/cognition/WeightContext.js
  src/lib/core/cognition/WeightStrategy.js
  src/lib/core/pouch/BasePouchCommand.js
  src/lib/core/pouch/PouchCLI.js
  src/lib/core/pouch/areas/BaseArea.js
  src/lib/core/pouch/areas/CognitionArea.js
  src/lib/core/pouch/areas/welcome/RoleListArea.js
  src/lib/core/pouch/areas/welcome/ToolListArea.js
  src/lib/core/pouch/commands/ActionCommand.js
  src/lib/core/pouch/commands/RecallCommand.js
  src/lib/core/pouch/commands/RememberCommand.js
  src/lib/core/pouch/commands/ToolCommand.js
  src/lib/core/pouch/layers/BaseLayer.js
  src/lib/core/pouch/layers/CognitionLayer.js
  src/lib/core/pouch/layers/ConsciousnessLayer.js
  src/lib/core/pouch/layers/RoleLayer.js
  src/lib/mcp/definitions/promptx_action.js
  src/lib/mcp/definitions/promptx_init.js
  src/lib/mcp/definitions/promptx_learn.js
  src/lib/mcp/definitions/promptx_recall.js
  src/lib/mcp/definitions/promptx_remember.js
  src/lib/mcp/definitions/promptx_think.js
  src/lib/mcp/definitions/promptx_toolx.js
  src/lib/mcp/definitions/promptx_welcome.js
  src/lib/mcp/server/FastMCPHttpServer.js
  src/lib/mcp/server/FastMCPStdioServer.js
Labels: priority: medium, type: enhancement
